### PR TITLE
Add tests for the encrypt_secrets option

### PR DESCRIPTION
**Pull request by mrj**
- Tests added for encrypted mode and the encryption tasks (the latter tests are skipped when testing under Rails < 4.1).
- Allowed the Gem to be used outside Rails, though testing is done under Rails.
- Disabled encryption if not running under Rails, or if the Rails Version is not at least 4.1.0.
- Added Rails 5.1 to the Appraisal list.
- To properly test encryption, the test secret changed from "test" to the 16-character Random32 string that had already been defined.
- Encryption Rake tasks updated to allow an optional list of model names to work on to be specified, rather than all models in the Rails file tree (needed this to have it work on the test models).
- Readme updated.

### CODE REVIEW

**Comment by jaredonline** [comment]
@mrj thanks for this! This is awesome. I'll give this a look over this week and merge it if everything looks good.

**Comment by mrj** [comment]
Great, thanks Jared.

Now that I've changed  ```set_google_secret``` to use ```save!``` rather than ```save!``` (before I was aware of #35), should I add a ```set_google_secret!``` alias? I think ```save!``` is better, because the only reason that it should fail is prior invalid attribute assignments, which you want to know about rather than have the secret silently not set.

**Comment by jaredonline** [comment]
👋 Sorry this has taken me so long to get to. I think using `save!` is fine. Raising an exception makes sense to me. I'll bump the version and roll a new version of this gem today.

**Comment by jaredonline** [comment]
@mrj just pushed out the new version. Thanks for your help!

**Pull request merged**
