### PR TITLE
Add new option img_size to let the user chose the size of the QR img

### PR DESCRIPTION
**Pull request by NormandLemay**

### CODE REVIEW

**Comment by jaredonline** [comment]
Hey there!

Thank you so much for this! Can you do two things for me?
- Can you add a test here https://github.com/jaredonline/google-authenticator/blob/master/spec/google_authenticator_spec.rb#L116
- Can you add documentation here: https://github.com/jaredonline/google-authenticator/blob/master/README.md

Thanks!

**Comment by NormandLemay** [comment]
No problem I will do it

**Comment by jaredonline** [comment]
Soo this has been here for over a year ]= Sorry ]= Can you push a small whitespace change commit to kick off Travis and see if the build passes and I'll merge it?

**Comment by jaredonline** [comment]
@NormandLemay looks like there's some conflicts, would you might taking a look at those?

**Comment by NormandLemay** [comment]
@jaredonline You may reject this pull request because is actually fixed by @mhickman in the pull request #36

**Pull request closed without merging**
