### PR TITLE
Add an option to store secrets in encrypted form

### PR DESCRIPTION
**Pull request by mrj**
[This](https://hackaday.com/2017/10/16/inside-two-factor-authentication-apps/) article made me aware that if an app's database is compromised (common in a hack), the Google secrets stored in the database will allow the attackers to bypass the 2FA it provides.

Since the ```config/secrets.yml``` file, or just the ```secret_key_base```, is normally handled more securely than the database, often by storing them only in memory, it would be worthwhile to encrypt the Google secret fields using the ```secret_key_base```.

This PR implements an ```:encrypt_secrets``` option that does just this, along with Rake tasks to encrypt existing secrets, and to re-encrypt the secrets if the ```secret_key_base``` needs to change.

No tests have been added yet. I can write them if the functionality is deemed worthwhile, and if a best approach is settled on.

### CODE REVIEW

**Comment by jaredonline** [comment]
Wow this is great! Thanks @mrj! I'm currently traveling for work, but will take a look at this in a couple of days, if that's alright with you.

**Comment by jaredonline** [comment]
Hey @mrj looks like the build is failing. Do you mind taking a look and seeing if you can get it to pass and update the pull request?

**Comment by mrj** [comment]
I think the following should fix it Jared.

**Comment by jaredonline** [comment]
Ah, I see. Is there a way to use `ActiveSupport::MessageEncryptor` without having to pull in all of rails? That's a pretty big dependency to add.

**Comment by mrj** [comment]
Jared, the ```rails``` Gem brings in Railtie, which allows the rake tasks to be run with the ```rails``` command, and be added to the ```rails -T``` list.

Is this Gem designed to be commonly used outside a Rails app, or are you thinking about the efficient loading of the test environment?

**Comment by jaredonline** [comment]
@mrj the intent was to keep the size of the gem down in general and pull in as few dependencies as possible.

But, the README does say its for tying to a Rails ActiveRecord integration. So I'll merge this as is. If you can think of a way in the future to not pull in all of Rails, that'd be cool. I'm going to merge this, then cut a new version of the gem at `1.4.0` since this creates new functionality.

**Comment by mrj** [comment]
Jared, I'm not sure whether requiring the rails gem brings in all rails components or just the integrating objects.

Thanks for deciding to integrate. I'd like to add some tests for encrypted mode first.

**Comment by mrj** [comment]
Oops, too late. I'll still write some tests and put them on anew PR.

**Comment by mrj** [comment]
Are you happy with the ```google_secret_value``` being made a public method, so that the 16-character secret can be accessed independently of the column name and encryption status? Calling this ```google_secret``` would make it harder to get the raw column value if the default column name is used.

**Comment by jaredonline** [comment]
Oh whoops! I thought I did see tests for the encryption. Yea, adding some would be great. Moving `google_secrete_value` to a public method is fine [=

**Pull request merged**
