### PR TITLE
Support rotp 5 plus

### PR DESCRIPTION
**Pull request by daniel-casey**
Updated to support the changes in rotp 5+

As rotp 6 contains potentially breaking changes (defaults to 32 character secret, drops support for Ruby <2.3) it probably merits bumping the version to 3.0

### CODE REVIEW

**Comment by daniel-casey** [comment]
@jaredonline It looks like Travis is no longer connected, so I can't see whether this is passing or failing. Either way hopefully this is a better starting point for getting this merged.

**Comment by jaredonline** [comment]
@daniel-casey It looks like Travis no longer provides free builds for open source. I'm in the process of trying to get CircleCI to do the matrix build. Once that works, we should be able to run your branch against it.

**Comment by jaredonline** [comment]
@daniel-casey, can you push a new commit to this and see if it builds on CircleCI? You may need to merge master first.

**Comment by jaredonline** [comment]
Oh; I just noticed this is a PR against `2.0-stable`; let's make it be against `master` and I'll cut `3.0` from that.

**Comment by daniel-casey** [comment]
@jaredonline I've rebased this onto master, resolved the conflicts and changed the PR to point to master. CircleCI doesn't seem to have run - am I missing something, or do you maybe need to enable "Build forked pull requests"? https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/

**Comment by jaredonline** [comment]
@daniel-casey thanks for helping me troubleshoot this. I've enabled builds for forked branches. Let's see if a commit will trigger a build? If not I'll just pull your build and run it manually 🤷

**Comment by daniel-casey** [comment]
@jaredonline Sweet - I push an empty commit and Circle ran successfully.

**Review by jaredonline — APPROVED** [review]
Thanks for your patience on this!

**Comment by jaredonline** [comment]
@daniel-casey is there more that should be put in before cutting a `3.0.0` version?

**Comment by daniel-casey** [comment]
@jaredonline This is looking good to me. Maybe you can add the small change from PR #62 directly rather than waiting for them to rebase? I haven't seen the issue in PR #56 myself, but maybe do the same for that one?

Once you get 3.0.0 up I'll drop it into a real project and try it out.

**Comment by johan-smits** [comment]
@jaredonline can we expect a release of the gem?

**Comment by jaredonline** [comment]
@daniel-casey @johan-smits  I just released 3.0. Thanks for your help and patience [=

**Comment by daniel-casey** [comment]
@jaredonline the change to use `ActiveSupport.on_load(:action_controller)` seems to cause RailsAdapter::LoadedTooLateError when running rspec under Rails 7. The error is not raised in the same application on Rails 5.2, so possibly something to do with the switch to zeitwerk in Rails 7.

Any idea how to fix / avoid this?

**Comment by jaredonline** [comment]
@daniel-casey what version of Ruby? It's interesting that the tests [passed in CircleCI](https://app.circleci.com/pipelines/github/jaredonline/google-authenticator/52/workflows/9999f28c-00c4-4552-874f-afdd4d028774/jobs/218)

Can you push a failing test as a PR so I can look?

**Comment by jaredonline** [comment]
@daniel-casey Oh I see, you mean if you install this gem in Rails 7.0 then run rspec, the tests fail with that error. I haven't used this with Rails 7.0 before (honestly I haven't used it since Rails 3.0). 

I'll poke around next week and see if I can figure it out.

**Pull request merged**
